<?php

namespace Hegentopf\Tests\queryBuilder;

use Hegentopf\EasyOrm\db\DbModel;
use Hegentopf\EasyOrm\db\DbColumn;
use Hegentopf\EasyOrm\queryBuilder\DbExpression;

/**
 * DbModel for table "join_db" (generated from database "inkubator")
 * Automatically generated by DbModelCreator v0.0.0 on 2025-12-26 20:59:36
 *
 * -----------------------
 * Getters: retrieve column values
 * -----------------------
 * @method int getId()
 * @method int getTestSpalte()
 * @method int getTestId()
 *
 * -----------------------
 * Setters: set column values
 * -----------------------
 * @method $this setId( int|DbExpression $id )
 * @method $this setTestSpalte( null|int|DbExpression $testSpalte )
 * @method $this setTestId( null|int|DbExpression $test_id )
 *
 * -----------------------
 * Columns: static DbColumn for query building
 * -----------------------
 * @method static DbColumn id()
 * @method static DbColumn testSpalte()
 * @method static DbColumn test_id()
 */
class JoinTestModel extends DbModel
{

    // -----------------------
    // Properties representing the database columns
    // -----------------------

    /**
     * @var int id column
     * DB Type: int(11)
     * Primary Key
     * Auto-increment
     */
    protected int $id = 0;

    /**
     * @var int|null testSpalte column
     * DB Type: int(11)
     * Nullable: yes
     */
    protected null|int $testSpalte = 0;

    /**
     * @var int|null test_id column
     * DB Type: int(11)
     * Nullable: yes
     */
    protected null|int $test_id = 0;


    protected static ?string $table = 'joinTest';

    protected static ?string $primaryKey = 'id';

    /**
     * @var array|string[] Column types for internal casting
     */
    protected static array $columnTypes = [
        'id' => 'int(11)',
        'testSpalte' => 'int(11)',
        'test_id' => 'int(11)',
    ];
}
